### ISSUE TITLE
Properties not included in create/update calls

### ISSUE THREAD

**Issue by jonathansimmons** [HubSpot/hubspot-api-ruby#121]
We have an app using this gem and we've more or less copied some of the classes from the sample apps like: https://github.com/HubSpot/hubspot-api-ruby/blob/3b01420a4810e7c57fa15d8234c1eb0d1c5a56bd/sample-apps/contacts-app/app/lib/services/hubspot/contacts/update.rb

However, all of the sudden when trying to create or update a record (company, contact, etc) the properties we're sending in the `SimplePublicObjectInput` appear to not be seen during the call. 

We've concluded this because of the following error:

```bash
Response body: {"status":"error","message":"No properties found to update, please provide at least one.","correlationId":"051c4a22-880f-4f6b-84f9-a71edb63abc7","context":{"properties":["{}"]},"category":"VALIDATION_ERROR"}
```

However, when we debug the properties they are clearly there: 

```ruby
{:application_identifier=>49,
 :firstname=>"some",
 :lastname=>"user",
 :email=>"email@email.com",
 :permission=>"account",
 :current_sign_in_at=>1626220800000,
 :last_sign_in_at=>1626048000000,
 :subscription_id=>"sub_JAZS20qCxjvtwK",
 :subscription_status=>"active",
 :invitation_accepted_at=>1616457600000}
```

I'm not sure what changed to cause this.

Can anyone help?

Versions: 
Rails: 6.1
Ruby: 3.0.0
hubspot_api-ruby: 10.1.1

**Comment by dtakeshta** [comment]
I know this is an old issue, but I wanted to point out why this isn't working just in case others view this in the future.  The sample that is provided in the issue will lead you astray.

`update` accepts `ID`, `SimplePublicObjectInput`, `opts`

The example passes `SimplePublicObjectInput` as a hash with a key of `body`

From the Hubspot API docs

```
Hubspot::Crm::Contacts::BasicApi.new.update("contactId", simple_public_object_input, auth_names: "hapikey")
```

Hope it helps someone!

**Comment by jonathansimmons** [comment]
Dang... I've not tested this but your observation is correct. I'm not sure how it ever worked given this discovery.

I'll test sometime in the next week or so and report back.
