### ISSUE TITLE
`Hubspot::Crm::Contacts::GDPRApi` not up to date with API docs

### ISSUE THREAD

**Issue by elleaiello** [HubSpot/hubspot-api-ruby#125]
The `Hubspot::Crm::Contacts::GDPRApi` class is not up to date with the latest API. See [changelog](https://developers.hubspot.com/changelog/changes-to-the-gdpr-deletion-endpoints-for-the-crm-contact-object-api).

Over [here](https://github.com/HubSpot/hubspot-api-ruby/blob/master/lib/hubspot/codegen/crm/contacts/api/gdpr_api.rb#L11), the `Hubspot::Crm::Contacts::GDPRApi` class is using the old endpoint, i.e. `DELETE '/crm/v3/objects/gdpr/contacts/{contactId}'`, versus the [docs](https://developers.hubspot.com/docs/api/crm/contacts), which is using `POST
/crm/v3/objects/contacts/gdpr-delete`.

<img width="957" alt="Screenshot 2021-12-13 at 16 00 43" src="https://user-images.githubusercontent.com/14853243/145825863-1c426c0c-3ac0-4e29-a39f-81f0100e88a1.png">

Thus when using the gem, I get a 404 and it raises the following error: `Hubspot::Crm::Contacts::ApiError: Error message: the server returns an error`.

Please could you update the gem. Thanks.

**Comment by plaurynovich-hubspot** [comment]
It should be fixed now. Thank you.
