### ISSUE TITLE
`Marketing::Transactional` uninitialized constant

### ISSUE THREAD

**Issue by ccartano** [HubSpot/hubspot-api-ruby#126]
Hello, 

Im trying to send transactional emails with the api, but accessing the marketing section of the code seems to not work.

```
NameError: uninitialized constant Hubspot::Marketing
Did you mean?  Margin
from (pry):1:in `<main>'
```

Any ideas? Is this still maintained?

**Comment by plaurynovich-hubspot** [comment]
Hi, @ccartano. Could you provide some code to reproduce the error?

**Comment by ccartano** [comment]
I load in the gem, then call `Hubspot::Marketing::Transactional` but get the error above. I am able to use the CRM or CMS modules but not the Marketing ones.

**Comment by plaurynovich-hubspot** [comment]
Hi @ccartano. I checked this
```ruby
require 'hubspot-api-client'

api = Hubspot::Marketing::Transactional::PublicSmtpTokensApi.new
```
with 11.1.1 version. It works fine for me. Could you tell, which version do you use or provide more details, please?

**Comment by ccartano** [comment]
@plaurynovich-hubspot Hi, that explains some of the issue. I found I was using v9.3.0 because there was some dependency conflict that was causing rails to pull in an older version. After updating the 'require_all' gem, I was then able to install 11.1.1 which then did work calling the `Hubspot::Marketing` module.


Thank you for following up and turns out its just user error!
