### ISSUE TITLE
id_property option removed from crm.contacts.basic_api.get_by_id in 12.0.0

### ISSUE THREAD

**Issue by Esaron** [HubSpot/hubspot-api-ruby#134]
While working through a dependency bump, I've discovered that support for the `id_property` option for https://www.rubydoc.info/gems/hubspot-api-client/12.0.0/Hubspot%2FCrm%2FContacts%2FBasicApi:get_by_id seems to have been removed in https://github.com/HubSpot/hubspot-api-ruby/pull/128 (https://github.com/HubSpot/hubspot-api-ruby/commit/3c399f9b4546867164beba6f4e704a9a16b62695). I can't find any documentation indicating that this was intentional, or any way to get the functionality back. We are currently relying on it in our integration with HubSpot.

Was this removal intentional? If so, can you provide any guidance on how to accomplish the same thing with the new version of the client?

**Comment by rsl** [comment]
yeh this breaks a lot of things for my company as well

**Comment by rsl** [comment]
question about how this code is generated/written? is a machine learning project doing this or are actual humans coding the api changes?

**Comment by plaurynovich-hubspot** [comment]
Hi, @Esaron. It should be fixed since v13.0.0. Thank you.

**Comment by plaurynovich-hubspot** [comment]
Hi, @rsl. It's automatically generated based on swagger files. Thank you.
