### ISSUE TITLE
uninitialized constant Hubspot::Crm::SimplePublicObjectInput

### ISSUE THREAD

**Issue by santiagosan93** [HubSpot/hubspot-api-ruby#137]
Hi there, I'm trying to update a customObject record and I keep getting uninitialized constant for `Hubspot::Crm::SimplePublicObjectInput`([class used by the documentation](https://developers.hubspot.com/docs/api/crm/crm-custom-objects)). Ive noticed that for standard objects there is always the name of the object before the `SimplePublicObjectInput` eg Hubspot::Crm::`Contacts`::SimplePublicObjectInput

version:`hubspot-api-client (13.0.0)`
environment: Rails

Am I missing something here? 

```ruby
properties = { "my_super_property": "20" }
simple_public_object_input = Hubspot::Crm::SimplePublicObjectInput.new(properties: properties)
```

**Comment by plaurynovich-hubspot** [comment]
Hi, @santiagosan93. There is no `Hubspot::Crm::SimplePublicObjectInput` but there is `Hubspot::Crm::Objects::SimplePublicObjectInput`. We'll fix a documentation code snippet, thank you.

**Comment by santiagosan93** [comment]
Thank you 🙏

**Comment by plaurynovich-hubspot** [comment]
It should be fixed now.

**Comment by SeanRoberts** [comment]
Has this been deprecated?

**Comment by ottony** [comment]
@plaurynovich-hubspot Has this been deprecated?

**Comment by SeanRoberts** [comment]
@ottony I ended up uninstalling this gem and just writing my own simple wrapper for the endpoints I needed. The new endpoints are much simpler to work with so it's not a lot of effort to just use Faraday or the HTTP Client of your choice.
