### ISSUE TITLE
It does not work with Ruby 3.x with `undefined method `encode' for URI:Module` error.

### ISSUE THREAD

**Issue by pokohide** [HubSpot/hubspot-api-ruby#138]
Hi, there.

I'm trying to upgrade to Ruby 3.x, but `hubspot-api-client` gem uses `URI#encode` internally, so I get the following error and it does not work.

```
undefined method `encode' for URI:Module
```

We will monkey patch this Gem to fix it, but we are hoping it will fixed by the Gem itself.

## Environment

```
hubspot-api-client: 13.0.0
ruby: 3.0.4
```

Thank, you.

**Comment by plaurynovich-hubspot** [comment]
Hi @pokohide. It should work for both v2 and v3 ruby since 13.1.0. Thank you.
