### ISSUE TITLE
`properties` didn't work in `Hubspot::Crm::Companies::BasicApi.new.get_by_id`

### ISSUE THREAD

**Issue by Yuji-Kuroko** [HubSpot/hubspot-api-ruby#140]
Hi there,

The API document said, `Hubspot::Crm::Companies::BasicApi.new.get_by_id` accept `properties` Array type.
But the properties option ignored.

I tried comma separated of String, So successed.

e.g. 
```
# NG
properties: ["name", "custom_label"]
# OK
properties: "name,custom_label"
```

## Environment

```
hubspot-api-client: 13.1.0
ruby: 3.1.2
```

**Comment by plaurynovich-hubspot** [comment]
Hi, @Yuji-Kuroko. It should be fixed since 13.2.0. Thank you.
