### ISSUE TITLE
Reduce memory consumption

### ISSUE THREAD

**Issue by pmackay** [HubSpot/hubspot-api-ruby#141]
While testing this gem, I am noticing it has some memory consumption issues:

1. The use of require_all seems to result in large memory allocations. I ran `bundle exec derailed bundle:mem` using [derailed_benchmarks](https://github.com/zombocom/derailed_benchmarks) and got:
```
  hubspot-api-client: 62.7031 MiB
    ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/crm/extensions/accounting/api/callbacks_api.rb: 2.4844 MiB
    ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/crm/extensions/accounting/models/invoice_pdf_response.rb: 1.5625 MiB
    ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/automation/actions/api_client.rb: 1.4531 MiB
      typhoeus: 1.4375 MiB (Also required by: ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/cms/audit-logs/api_client.rb, ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/cms/blogs/authors/api_client.rb, and 45 others)
        ethon: 1.3594 MiB
          mime/types/columnar: 1.0156 MiB
            mime/types: 1.0156 MiB
              mime/types/registry: 0.8438 MiB
    ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/cms/blogs/blog-posts/models/blog_post.rb: 0.5156 MiB
    ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/cms/blogs/tags/models/attach_to_lang_primary_request_v_next.rb: 0.5 MiB
    ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/cms/blogs/blog-posts/models/attach_to_lang_primary_request_v_next.rb: 0.4375 MiB
    ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/cms/blogs/tags/models/tag.rb: 0.3125 MiB
    ruby/2.7.5/lib/ruby/gems/2.7.0/gems/hubspot-api-client-12.0.0/lib/hubspot/codegen/cms/domains/models/domain.rb: 0.3125 MiB
```
Then ran `bundle exec derailed bundle:objects` and got:
```
allocated memory by gem
-----------------------------------
  91075150  dead_end-3.1.1
   5301198  mime-types-3.4.1
   4075247  require_all-3.0.0
   3677771  lib
   3371273  hubspot-api-client-12.0.0
```
Note: dead_end is used by derailed_benchmarks, other than that the top 4 items (apart from lib) are from hubspot-api-client.

I appreciate many of the classes are generated files, but is it possible for them to only [require what they need](https://janko.io/require-only-what-you-require/)?

---

2. The dependency on typhoeus pulls in an extra HTTP library that no other runtime gem requires. [This post](https://www.mikeperham.com/2016/02/09/kill-your-dependencies/) by Mike Perham recommends that gems should only use Net::HTTP, to avoid apps pulling in a bunch of different HTTP libraries. Please could you migrate this to use Net::HTTP only?

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @pmackay 
Thanks for your issue.
We took into account your comments and reduced memory consumption starting from the version [v15.0.0](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v15.0.0).
