### ISSUE TITLE
get_by_name raises `ArgumentError` even when required parameter is present

### ISSUE THREAD

**Issue by Sokre95** [HubSpot/hubspot-api-ruby#159]
Example: 

`api_client.crm.properties.core_api.get_by_name(object_type: 'objectType', property_name: 'property')`

returns

`core_api.rb:256:in 'get_by_name_with_http_info': Missing the required parameter 'property_name' when calling CoreApi.get_by_name (ArgumentError)`

**Comment by plaurynovich-hubspot** [comment]
Hi, @Sokre95. It should be fixed with v14.5.2. Thank you.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @Sokre95 
Could you check the latest version?
Thank you.
