### ISSUE TITLE
NoMethodError: undefined method `configure' for Hubspot:Module on tag 15.0.0

### ISSUE THREAD

**Issue by DiegoOrejuela** [HubSpot/hubspot-api-ruby#162]
Hi guys

New version broke configure method on Hubspot module.

¿What is the new way for use this?

Thanks, nice job!

**Comment by plaurynovich-hubspot** [comment]
Hi @DiegoOrejuela. Hubspot.configure has been removed since v15.0.0. You can pass some params to Hubspot::Client.new() instead:
```ruby
require 'hubspot-api-client'
client = Hubspot::Client.new(access_token: 'your_access_token')
```
or you can access your local configuration file with
```ruby
config = client.crm.contacts.basic_api.api_client.config
```
if you need to. Thank you.

**Comment by DiegoOrejuela** [comment]
Ok, thanks @plaurynovich-hubspot
