### ISSUE TITLE
 Breaking Changes: uninitialized constant Hubspot::Crm::Contacts

### ISSUE THREAD

**Issue by adifsgaid** [HubSpot/hubspot-api-ruby#165]
**Braking Changes:**

After upgrading to the latest version mapping to the Contacts model returns uninitialized.

**Comment by plaurynovich-hubspot** [comment]
Hi, @adifsgaid. Could you provide a code snippet that you are using, please? Thank you.

**Comment by adifsgaid** [comment]
Hello @plaurynovich-hubspot, thanks for getting back to me, the snippet I use, it's for handling all Error from the hubspot api, the current version i'm using is `hubspot-api-client (14.5.2)`

This are the snippet, i'm using:
` Hubspot::Crm::Schemas::ApiError`
`Hubspot::Crm::Contacts::ApiError`

**Comment by plaurynovich-hubspot** [comment]
Hi, @adifsgaid. Can you handle these errors with a block?
```ruby
api_responce = client.crm.contacts.basic_api.get_page { |error| error }
```
Thank you.

**Comment by Sokre95** [comment]
@plaurynovich-hubspot Can we still handle api errors like this? 
```
begin 
  client.crm.contacts.basic_api.get_page
rescue Hubspot::Crm::Contacts::ApiError =̣> e
  # do something with the error
end
``` 
That way we don't need to use block in actual api call and we can handle errors elsewhere
