### ISSUE TITLE
Hubspot::Crm::Timeline::TimelineEvent not working

### ISSUE THREAD

**Issue by dannio** [HubSpot/hubspot-api-ruby#167]
Followed the examples on the doc after the update and doing:

```
api_client = Hubspot::Client.new(access_token: access_token)

tokens = {
  "what_happened": "Tested via HS site",
}

body = {event_template_id: "*template ID*", email: "xxx@gmail.com", tokens: tokens}
api_response = api_client.crm.timeline.events_api.create(body: body)
puts api_response
```

return the error:

Response body: {"status":"error","message":"Invalid input JSON on line 1, column 77: Cannot build TimelineEvent, some of required attributes are not set [eventTemplateId]","correlationId":"8b98f891-897e-4209-b43f-b45f3a30369c"}

Also, on the docs it references api_client.crm.timeline.events.events_api.create(body: body), which I don't think exists?

**Comment by rai-hi** [comment]
I had a similar issue recently, and it worked when changing the hash key to camel case, e.g.:

```
body = {eventTemplateId: "*template ID*", email: "xxx@gmail.com", tokens: tokens}
```

Worth a try?

**Comment by dannio** [comment]
omg that worked. @rai-hi you're a lifesaver. The docs on HubSpot are an absolute mess lol

**Comment by dannio** [comment]
@alzheltkovskiy-hubspot thanks. Seems to be fine now.
