### ISSUE TITLE
New updates breaks older apps using Hubspot initializer

### ISSUE THREAD

**Issue by dannio** [HubSpot/hubspot-api-ruby#168]
The previous versions all had the option to set a global initializer:

```
Hubspot.configure do |config|
  config.access_token = env['access_token']
  config.params_encoding = :multi
end
```

After the update, it breaks my application with:
undefined method `configure' for Hubspot:Module (NoMethodError)

Previous version:
hubspot-api-client-14.3.0

New version:
hubspot-api-client-15.0.1

**Comment by Petercopter** [comment]
Same here. Can we get some migration instructions for moving to the new configuration?

**Comment by Sybe** [comment]
I am experiencing this too. I'm trying to upgrade from version 14, but so much has changed and no real guidance is available.

**Comment by rai-hi** [comment]
Hey @Sybe - feel free to post some examples here and I might be able to help - I've migrated a large number of these now so might know what you need!

**Comment by Petercopter** [comment]
@rai-hi How are you handling the OAuth callback to create a token? The new docs skip right past trading a code for a token...

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone
Workable example of how to use `OAuth` is [here](https://github.com/HubSpot/sample-apps-oauth/tree/main/ruby). Also in it, you can get acquainted with the new syntax.
