### ISSUE TITLE
Unclear how to use filters in latest versions

### ISSUE THREAD

**Issue by rai-hi** [HubSpot/hubspot-api-ruby#169]
Previously, I created filters like so:

```
has_analytics_source_filter = ::Hubspot::Crm::Deals::Filter.new(
  operator: 'HAS_PROPERTY',
  property_name: 'hs_analytics_source'
)
```

After updating to a more recent version, this gives `uninitialized constant Hubspot::Crm`. I'm struggling to find any documentation or examples of filtering with the latest versions of the gem. Are these available anywhere?

Thanks!

**Comment by orkhan** [comment]
same issue with Rails 6.1.2 and Ruby 3.1.2

```
NameError: uninitialized constant Hubspot::Crm::Contacts::Filter

      filter = ::Hubspot::Crm::Contacts::Filter.new(property_name: 'email', operator: 'EQ', value: @user.email)
                                       ^^^^^^^^
Did you mean?  File
               Fiber

```

**Comment by vuhminh** [comment]
same with `client.crm.contacts.search_api.do_search`, trying

```
filter = {
        property_name: property,
        operator: 'EQ',
        value: @email.downcase
      }

      filter_group = {
        filters: [filter]
      }

      body = {
        filter_groups: [filter_group]
      }

client.crm.contacts.search_api.do_search(body: body)
```

ignores search params

**Comment by plaurynovich-hubspot** [comment]
Hi @rai-hi, @orkhan, @vuhminh. You can use something like this:
```ruby
filter = {
  propertyName: 'email',
  operator: 'EQ',
  value: 'your_email'
}

filter_group = {
  filters: [filter]
}

body = {
  filterGroups: [filter_group]
}

client.crm.contacts.search_api.do_search(body: body)
```
Thank you.

**Comment by StefanHagen** [comment]
@plaurynovich-hubspot I think it's important to state the change from `filter_groups` to `filterGroups`. This is quite a change, since you can't for example create a `PublicObjectSearchRequest` with a `filterGroups` key. I used to pass an object like

```
filters = {
  filter_groups: [
    {
      filters: [
        {
          value: 'stefan@ikbenfrits.nl',
          propertyName: 'email',
          operator: 'EQ'
        }
      ]
    }
  ],
  limit: 1
}

public_object_search_request = Hubspot::Crm::Contacts::PublicObjectSearchRequest.new(filters)
```

However creating the `public_object_search_request` expects a `filter_groups` key, so does not work with `filterGroups`. Anyway, your code snippet above works, so I'll use that for now, but note that it breaks some other stuff ;) Thanks for replying to this issue, the code above solved a problem I had!

**Comment by scottbullard** [comment]
@vuhminh I discovered that you need to both camelCase the object property names as @plaurynovich-hubspot noted, but omit the `body` property from the example `do_search()` call:

> ```ruby
> filter = {
>   propertyName: 'email',
>   operator: 'EQ',
>   value: 'your_email'
> }
> 
> filter_group = {
>   filters: [filter]
> }
> 
> body = {
>   filterGroups: [filter_group]
> }
> 
> client.crm.contacts.search_api.do_search(body)
> ```

**Comment by rai-hi** [comment]
> Thank you for the advice @plaurynovich-hubspot. That was very helpful and I've been able to fix that problem.
> 
> I have now encountered another issue whilst attempting to update my code to the new format:
> 
> ```
> # Old version, worked okay
> api = ::Hubspot::Crm::Associations::BatchApi.new
> response = api.read('line_item', 'deal', {
>     body: {
>         inputs: [{id: 1}, {id: 2}, {id: 3}]
>     }
> })
> # => Worked fine with old library version
> 
> 
> # New version, gives argument error
> api = client.crm.associations.batch_api
> response = api.read('line_item', 'deal', {
>     body: {
>         inputs: [{id: 1}, {id: 2}, {id: 3}]
>     }
> })
> # => ArgumentError (wrong number of arguments (given 3, expected 0..1))
> ```
> 
> Any advice on how to use this method with the new format? Thanks so much

For anyone reading this and encountering the same problem with the new version, I solved this like so:

```
response = api.read(
                from_object_type: 'line_item', 
                to_object_type: 'deal', 
                batch_input_public_object_id: { inputs: [{id: 1}, {id: 2}, {id: 3}] }
              )
```
