### ISSUE TITLE
Hubspot::Crm::Contacts::AssociationsApi.get_all() not returning all Company associations

### ISSUE THREAD

**Issue by CChanHY** [HubSpot/hubspot-api-ruby#171]
When using the Ruby example here in the API documentation (https://developers.hubspot.com/docs/api/crm/contacts) (using the website test call feature)
```
require 'hubspot-api-client'

api_client = Hubspot::Client.new(access_token: 'YOUR_ACCESS_TOKEN')

api_response = api_client.crm.contacts.associations_api.get_all(contact_id: "61651", to_object_type: "company", limit: 500)
puts api_response
```
I receive 2 associated Companies, which is correct:
```
HTTP 200

{
  "results": [
    {
      "toObjectId": 9706190448,
      "associationTypes": [
        {
          "category": "HUBSPOT_DEFINED",
          "typeId": 279,
          "label": null
        }
      ]
    },
    {
      "toObjectId": 9723855655,
      "associationTypes": [
        {
          "category": "HUBSPOT_DEFINED",
          "typeId": 1,
          "label": "Primary"
        },
        {
          "category": "HUBSPOT_DEFINED",
          "typeId": 279,
          "label": null
        }
      ]
    }
  ]
}
```
However, when I run the same code locally, I only get 1 association back in the results:
```
[4] pry(main)> api_client = Hubspot::Client.new(access_token: 'my_token')
=> #<Hubspot::Client:0x000056214a81f300 @params={:access_token=>"my_token"}>
[5] pry(main)> api_response = api_client.crm.contacts.associations_api.get_all(contact_id: "61651", to_object_type: "company", limit: 500)
ETHON: performed EASY effective_url=https://api.hubapi.com/crm/v3/objects/contacts/61651/associations/company?limit=500 response_code=200 return_code=ok total_time=0.355959
=> #<Hubspot::Crm::Contacts::CollectionResponseAssociatedIdForwardPaging:0x000056214aa027d0
 @results=[#<Hubspot::Crm::Contacts::AssociatedId:0x000056214a9fb980 @id="9723855655", @type="contact_to_company">]>
```

I see that this gem is using the v3 API `https://api.hubapi.com/crm/v3/` and when I manually do a GET on this URL it does in fact return 1 result. If I do the same GET on the v4 API, I get the expected multiple results.

Does V3 need to be fixed? Or does this gem need to be updated to use V4? Or is there something I can do to get all the associated Companies?

**Comment by plaurynovich-hubspot** [comment]
Hi, @CChanHY. This gem should be updated to use V4. Thank you.

**Comment by CChanHY** [comment]
@plaurynovich-hubspot Any ETA on update to V4? And for now, is the returned association always going to be the Primary associated Company? What is to be expected?

**Comment by fsmanuel** [comment]
@plaurynovich-hubspot the `crm.associations` apis still use `v3`

https://github.com/HubSpot/hubspot-api-ruby/blob/master/lib/hubspot/codegen/crm/associations/api/types_api.rb#L54

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone
Could you check the latest version [16.3.0.](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v16.3.0)?
