### ISSUE TITLE
CRM association details missing between contacts and companies 

### ISSUE THREAD

**Issue by gkorban** [HubSpot/hubspot-api-ruby#188]
When calling the contacts.associations_api.get_all or companies.associations_api.get_all, I would expect the returned results to include information like the ID of the associated object(s), but the APIs return empty instances of `Hubspot::Crm::Contacts::AssociatedId` or `Hubspot::Crm::Companies::AssociatedId`.

For example, when getting companies associated with a contact:
> client = Hubspot::Client.new(access_token: 'access token')
=> #<Hubspot::Client:0x00005608130108a8 @params={:access_token=>'access token'}>
> associations = client.crm.contacts.associations_api.get_all(contact_id: '325551', to_object_type: 'company')
=> #<Hubspot::Crm::Contacts::CollectionResponseAssociatedIdForwardPaging:0x000056110801b2f0 @results=[#<Hubspot::Crm::Contacts::AssociatedId:0x000056110801a0f8>]>
> associations.results.each{|a| p a }
#<Hubspot::Crm::Contacts::AssociatedId:0x000056110801a0f8>

also when getting contacts associated with a company:
> associations = client.crm.companies.associations_api.get_all(company_id: '2209541162', to_object_type: 'contact')
=> #<Hubspot::Crm::Companies::CollectionResponseAssociatedIdForwardPaging:0x00007f076a5d3ae0
 @results=
  [#<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5cc1c8>,
   #<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5cb2a0>,
   #<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5ca1c0>,
   #<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5c92e8>,
   #<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5c8438>,
   #<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5c7510>]>
[6] pry(main)> associations.results.each{|a| p a }
#<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5cc1c8>
#<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5cb2a0>
#<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5ca1c0>
#<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5c92e8>
#<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5c8438>
#<Hubspot::Crm::Companies::AssociatedId:0x00007f076a5c7510>

**Comment by KillWolf** [comment]
Also facing this issue.

**Comment by xymbol** [comment]
I see the same when retrieving companies associated with deals.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone
I have fixed it
Could you check the [latest version](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v16.0.4), please?
