### ISSUE TITLE
Add support for marketing lists

### ISSUE THREAD

**Issue by gkorban** [HubSpot/hubspot-api-ruby#191]
It appears there is currently no support for accessing Hubspot's Lists API (any version). I understand the new version of the List API is still in development by Hubspot, but the older (current) version is still usable. Not providing any support for Lists is problematic for those of us looking to migrate to this new(er) gem from the hubspot-ruby gem.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @gkorban. At the moment, adding a marketing list is not a priority. At the moment we are closing the issue, but as soon as the situation changes we will reopen it again.
