### ISSUE TITLE
Add instructions for contributing

### ISSUE THREAD

**Issue by gkorban** [HubSpot/hubspot-api-ruby#196]
Please add instructions for contributing to the project into the README. Tips for how to build and test the project would be helpful, as well as any other important info like don't make changes in the codegen directory.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @gkorban. `SDK` is a set of tools for software development, that is, it is not really a project in the sense of the word. Therefore, all the necessary information for using the `SDK` is already in the `README`.
