### ISSUE TITLE
uninitialized constant Hubspot::OAuthHelper on 16.x

### ISSUE THREAD

**Issue by Petercopter** [HubSpot/hubspot-api-ruby#205]
Trying to upgrade from hubspot-api-ruby 14.x to 16.x, and I'm getting this error:

```
uninitialized constant Hubspot::OAuthHelper
```

It looks like the helper is in the codebase. I'm taking a wild guess that this is probably the culprit:

```
-    hubspot-api-client (14.5.2)
+    hubspot-api-client (16.2.0)
-      require_all (~> 3.0.0)
```

It's not being required correctly anymore.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @Petercopter 
Since version [v15.0.0](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v15.0.0), we have removed our own requires and now, in order to access custom classes, you need to call them explicitly.
Example:
```ruby
require 'hubspot/oauth_helper'
```
This was done in order to reduce memory consumption.
