### ISSUE TITLE
Calling `client.crm.contacts.basic_api.update` raises LoadError

### ISSUE THREAD

**Issue by wuputah** [HubSpot/hubspot-api-ruby#206]
Hi,

I was able to reproduce this regardless of what parameters I passed to the function:

```ruby
>> client.crm.contacts.basic_api.update
LoadError: cannot load such file -- hubspot/codegen/crm/contacts/models/contact_id
from ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
```

I was able to workaround the issue using the underlying `api` object, i.e. using `c.c.c.basic_api.api.update`.

Ruby 3.1.2
hubspot-api-client 16.2.0

**Comment by wuputah** [comment]
Heads up that I'm also getting this error when using `find_by_id`.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @wuputah 
c.c.c.basic_api.update has required parameters(client_id, body), if we try call 'update' without required parameters we get an error. Your request should be something like this:
```ruby
client.crm.contacts.basic_api.update(contact_id: 1, body: { properties: { email: "updated_email@mail.com" } })
```
About find_by_id, i think you mean get_by_id which also accepts required parameter(client_id)
More info [here](https://developers.hubspot.com/docs/api/crm/contacts) with examples.
I hope I was helpful to you, thanks.
