### ISSUE TITLE
How to get users by Email using get_by_id and query params id_property.

### ISSUE THREAD

**Issue by harssh** [HubSpot/hubspot-api-ruby#212]
Refer : https://github.com/HubSpot/hubspot-api-ruby/blob/master/lib/hubspot/codegen/settings/users/api/users_api.rb#L175

Document here https://developers.hubspot.com/docs/api/settings/user-provisioning
I tried multiple combinations of query params but get 

> "VALIDATION_ERROR","subCategory":"ValidationErrors.USER_ID_NOT_NUMERIC"

Trying below API endpoint

``` ruby
properties = {  id_property: "EMAIL" }
client.settings.users.users_api.get_by_id(user_id: "AdamTest@yabdabadoo.com", query_params: properties )
```
The above request makes the get request as "/settings/v3/usersAdamTest%40yabdabadoo.com" but it's not adding 
?id_property=EMAIL according to the document here https://developers.hubspot.com/docs/api/settings/user-provisioning

I tried tricking the Endpoint and 

``` ruby
client.settings.users.users_api.get_by_id(user_id: "AdamTest@yabdabadoo.com?idProperty=EMAIL", query_params: properties )
```
which does convert GET request to https://api.hubapi.com/settings/v3/users/AdamTest%40yabdabadoo.com%3FidProperty%3DEMAIL  still getting USER_ID_NOT_NUMERIC error.

Any suggestion/input or help is highly appreciated.

**Comment by R-montekaka** [comment]
checkout this one https://developers.hubspot.com/docs/api/crm/contacts

**Comment by harssh** [comment]
@R-montekaka Thank you for the reply. If you go through my explanation, I am working with Users, not contacts and looking for solution in that area.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @harssh 
Can you try something like this?
```ruby
from properties = {  id_property: "EMAIL" } to properties = {  idProperty: "EMAIL" }
```
I hope it will be useful for you.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @harssh 
Not quite so, if you pass a key word argument as shown in the [example](https://developers.hubspot.com/docs/api/settings/user-provisioning), then everything will work fine, but if you pass a hash, then you need to specify the desired key.
