### ISSUE TITLE
`get_all` method not working

### ISSUE THREAD

**Issue by jotolo** [HubSpot/hubspot-api-ruby#221]
```ruby
client = Hubspot::Client.new(access_token: 'your_oauth2_access_token')
all_contacts = client.crm.contacts.basic_api.get_all
```
Hi! Thanks for creating this Wrapper for Hubspot. We are trying to use it to rebuild our integration with it.

I have created a test account and a private app with it. I copied the token provided and initialised the client as the example shows.
The result is a 401 Unauthorised response.
You can use a brand new private app token to reproduce it. 
The strange thing is it works if you ask only for a page so, it seems something within the internal pagination process is failing maybe.

Library version: 16.4.0

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @jotolo
I have already tried to use it, for me it works well.
As i see you use `oauth2 access token`, it has `expire time`, perhaps your token expired.

**Comment by jotolo** [comment]
Hi @alzheltkovskiy-hubspot . Thanks for the quick reply. 
Sorry about the script, I just copied from the example. I use a private app access token, the token won't change in this case.
It is a brand new token from a brand new private app. 
The weird thing is it worked with my production token so, it seems something is going on with the tokens from test account and production accounts.
Another weird thing is that it worked if I requested for a page instead of using `get_all` method.
Did you tried creating a new account and a new test environment with a new private app? Something is off there.
In any case, it does seems like the problem is not with the library but with the Hubspot API or private apps. Not sure you can check it too. 
If not, please, feel free to close this ticket 👍 
Thanks for checking

**Comment by rempargo** [comment]
I'm having the same issue.
I have created an hubspot account, imported companies, created an private app to get a token, Set all READ permissions in the CRM module on TRUE.

Then I run the example code from the documentation

```
# Load the gem
require 'hubspot-api-client'

# Setup client
client = [Hubspot](https://www.rubydoc.info/gems/hubspot-api-client/16.4.0/Hubspot)::[Client](https://www.rubydoc.info/gems/hubspot-api-client/16.4.0/Hubspot/Client).[new](https://www.rubydoc.info/gems/hubspot-api-client/16.4.0/Hubspot/Client#initialize-instance_method)(access_token: 'your_access_token')

client.crm.companies.basic_api.get_page  # working

client.crm.companies.basic_api.get_all # NOT working
```

so the `get_page` method is working, but the `get_all` is not
you will see the following error:
```
Response body: {"status":"error","message":"Authentication credentials not found. This API supports both API Key and OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview","correlationId":"f0380460-936e-4474-b5b9-8ab0104c3a6b","category":"INVALID_AUTHENTICATION
```

I'm using  gem 'hubspot-api-client' version 16.4.0 on ruby 2.7.4 on macOS

**Comment by jotolo** [comment]
@rempargo The problem does exists, I tested it a couple of more time and it failed all of them. In the meantime my recommendation is you use a pagination logic to bring them all.

```ruby
class All
      MAX_PAGE_SIZE = 100

      def self.each(opts = {})
        client = ::Hubspot::Client.new(access_token: 'access_token')
        opts[:limit] ||= MAX_PAGE_SIZE
        after = nil

        loop do
          page_opts = opts.merge(after: after)
          page = client.crm.contacts.basic_api.get_page(page_opts)
          page.results.each { |contact| yield contact }
          paging = page.paging
          break if paging.nil?

          after = paging._next.after
        end
      end
    end
 ```
 
 I hope it helps 👍

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone. `api_client.crm.companies.basic_api` haven't method `get_all`, if you want use `get_all`, your request should be looks like `api_client.crm.companies.get_all`. This information should be useful.

**Comment by rikkiprince** [comment]
Why not just add:

```ruby
require 'hubspot/helpers/get_all_helper'
include Hubspot::Helpers::GetAllHelper
```
to the top of `owners_api.rb`? All the other objects that expost `.get_all` have it included.
