### ISSUE TITLE
README on do_search is incorrect

### ISSUE THREAD

**Issue by hugobytes** [HubSpot/hubspot-api-ruby#222]
This should be snake_cased:
```
body = {
  filter_groups:
    [
      {
        filters:[
          {
            value: timestamp,
            property_name: "lastmodifieddate",
            operator: "EQ"
          }
        ]
      }
    ]
}
```

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @hugobytes.
Shall you try example from `README` please and could you write what you got?

**Comment by javierrodriguez94** [comment]
I'm using just this gem, in the latest version in master.

**Comment by alzheltkovskiy-hubspot** [comment]
@javierrodriguez94. Perhaps you using old syntax that not working correctly since version `15.0.0`. Could you try to repeat the request exactly as shown in the example.
