### ISSUE TITLE
get_email_status looks not working in 16.4.0

### ISSUE THREAD

**Issue by bourg-ismael** [HubSpot/hubspot-api-ruby#224]
Hi,

I'm trying to upgrade to version 16.4.0. And we were using get_email_status method that looks broken in this version.

Here an exemple:
```ruby
email = 'test@test.com'
client = Hubspot::Client.new(access_token: HUBSPOT_ACCESS_TOKEN)
client.communication_preferences.status_api.get_email_status(email)
```

And the result is:
```
TypeError: no implicit conversion of Symbol into Integer
from /Users/bourgismael/.rvm/gems/ruby-2.7.2/gems/hubspot-api-client-16.4.0/lib/hubspot/discovery/base_api_client.rb:135:in `[]'
```

I tried to override base_api_client to see what I get
```
def define_api_methods
        api_methods.each do |api_method|
          self.class.define_method(api_method) do |params = {}, &block|
            params_with_defaults = params
            params_with_defaults[:opts] ||= {}
```

as params_with_defaults I get `test@test.com`

Is it me that doesn't calls correctly or is that a problem with this gem version ?

Thanks

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @bourg-ismael.
We working on it.

**Comment by alzheltkovskiy-hubspot** [comment]
HI @bourg-ismael.
Here is the workable example:
```ruby
require 'hubspot-api-client'

client = Hubspot::Client.new(access_token: "YOUR_ACCESS_TOKEN")

email = 'test@test.com'
responce = client.communication_preferences.status_api.get_email_status(email_address: email)
puts responce
```
More info you can see in [documentation](https://developers.hubspot.com/docs/api/marketing-api/subscriptions-preferences).

**Comment by bourg-ismael** [comment]
Thank you @alzheltkovskiy-hubspot, it works perfectly !
