### ISSUE TITLE
Refresh token API broken in 16.4.0

### ISSUE THREAD

**Issue by macmartine** [HubSpot/hubspot-api-ruby#241]
client = ::Hubspot::Client.new(access_token: hs.access_token)

client.o_auth.refresh_tokens_api.get_refresh_token

LoadError: cannot load such file -- hubspot/codegen/oauth/models/token

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @macmartine. You try to use method `get_refresh_token` without `token` parameter. [Here](https://developers.hubspot.com/docs/api/oauth/tokens#endpoint?spec=DELETE-/oauth/v1/refresh-tokens/{token}) you can find more information. Starting from version 17.0.0, the naming for the  `tokens_api` methods will be changed.
