### ISSUE TITLE
Error requiring path after upgrading from 16.4 to 17.0

### ISSUE THREAD

**Issue by oboxodo** [HubSpot/hubspot-api-ruby#245]
After upgrading from 16.4 to 17.0 I'm getting this error:

```ruby
client = Hubspot::Client.new(access_token: my_access_token)
generate_api = client.conversations.visitor_identification.generate_api
# throws this error:
#<LoadError: cannot load such file -- hubspot/codegen/conversations/visitor-identification/api/generate_api>
```

It looks like this code might be outdated:

https://github.com/HubSpot/hubspot-api-ruby/blob/4f1b8d6652120b0e83cb5ecc8be5bcf5ad45601b/lib/hubspot/helpers/path.rb#L15-L21

Apparently, [this commit](https://github.com/HubSpot/hubspot-api-ruby/commit/fbf82239deb34fdec3e3facdbd98ea29963bface) has renamed a bunch of files/directories changing `-` with `_` so now the substitutions being made in the method above might not be needed anymore.

**Comment by lpar** [comment]
Similar problem here:

```ruby
client = Hubspot::Client.new(access_token: ACCESS_TOKEN)
begin
  properties = client.crm.properties.core_api.get_all
  pp properties
rescue Exception => e
  pp e
end
```

```
#<LoadError: cannot load such file -- hubspot/codegen/crm/properties/models/object_type>
```

[Which is true](https://github.com/HubSpot/hubspot-api-ruby/tree/master/lib/hubspot/codegen/crm/properties/models), and there doesn't seem to be a file matching `object*type` anywhere in the library code.

In my case it doesn't seem to work in 16.4 either.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @lpar it's not a similar problem, you trying call method without required `object_type` param, this param should contain one of the entity types you need like(`"deals", "contacts", ect`).
If you want get all `properties` of `deals` your request should be looks like this:
```ruby
properties = client.crm.properties.core_api.get_all(object_type: "deals")
```
I hope this information proves to be helpful.

**Comment by oboxodo** [comment]
Thanks for merging a fix!
