### ISSUE TITLE
Upgrate hubspot-api from 16.4.0 to 17.0.0

### ISSUE THREAD

**Issue by ritamma** [HubSpot/hubspot-api-ruby#246]
Hello, I use method associations_api to associate a deal with another object.
But in release https://github.com/HubSpot/hubspot-api-ruby/commit/c93dd5d8ef4cc0d5b1f0b42b2b575809d350793e this method (crm.deals.associations_api.) was removed.
What can I use instead of this method to create associations.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @ritamma. You can find the information you are interested in [here](https://developers.hubspot.com/docs/api/crm/associations).
