### ISSUE TITLE
Incorrect auth_settings hash for developer_api_key 

### ISSUE THREAD

**Issue by vvitto** [HubSpot/hubspot-api-ruby#252]
I'm trying to manage webhook subscriptions via API and with according to [official documentation](https://developers.hubspot.com/docs/api/developer-tools-overview#developer-api-keys) I created developer api key. But when I try to fetch any data using this code I get 401 error from server.
```
client = Hubspot::Client.new(developer_api_key:)
client.webhooks.subscriptions_api.get_all(app_id:) # this raises error
```

More over in my logs I see the request that is made by the client doesn't contain value in hapikey query parameter. Example: 
`https://api.hubapi.com/webhooks/v3/2031234/subscriptions?hapikey=` - `hapikey` is empty.

I've researched a little bit and found out that problem is [here](https://github.com/HubSpot/hubspot-api-ruby/blob/c5e80e9650716db5d27c233e55ef7494966a821b/lib/hubspot/discovery/base_api_client.rb#L49)
line 49 should set 'developer_hapikey' instead of 'hapikey' one more time.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @vvitto. We will fix this inconsistency and release a new version next week.

**Comment by vvitto** [comment]
Maybe it has a sense to leave the ticket open until the release.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @vvitto. Could you please check the latest [version](https://github.com/HubSpot/hubspot-api-ruby/tree/v17.1.1)?

**Comment by vvitto** [comment]
@alzheltkovskiy-hubspot thanks, seems all good!
