### ISSUE TITLE
uninitialized constant Hubspot::Crm::Associations::V4::CollectionResponseAssociationSpecWithLabelNoPaging

### ISSUE THREAD

**Issue by pohl989** [HubSpot/hubspot-api-ruby#254]
When attempting to get the [Association schema definitions ](https://developers.hubspot.com/docs/api/crm/associations)

`api_client = Hubspot::Client.new(access_token: 'YOUR_ACCESS_TOKEN')`

`api_response = api_client.crm.associations.v4.schema.definitions_api.get_all(from_object_type: "fromObjectType", to_object_type: "toObjectType")`

It  returns  a 200 http response.  It fails when processing the response.

## Error

`NameError (uninitialized constant Hubspot::Crm::Associations::V4::CollectionResponseAssociationSpecWithLabelNoPaging)`

**Comment by CraftyBeer** [comment]
HUGE FIX HERE! Thanks @pohl989 !!! Hubspot team can you please merge this one in!

**Comment by pohl989** [comment]
@alzheltkovskiy-hubspot any updates on the related PR?

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @pohl989. We are currently working on this problem. We will definitely let you know when there is news.

**Comment by heymarkreeves** [comment]
Just ran into this. Any updates? I can't define associations without it.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone. Still in progress.

**Comment by heymarkreeves** [comment]
This worked in my standard sandbox but not in production—this is blocking us from consistently deploying schema changes.

**Comment by geo1004** [comment]
Any news ? I'm unable to fetch associations definitions from Hubspot, we're stuck

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone. We plan to resolve this issue with the release of a new version by the end of next week.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone. Could you please check the latest [version](https://github.com/HubSpot/hubspot-api-ruby/tree/v18.0.0)?
