### ISSUE TITLE
New `export` API support

### ISSUE THREAD

**Issue by pyromaniac** [HubSpot/hubspot-api-ruby#258]
Hello there,

Are there any plans to add the new CRM exports API support any time soon? If yes, can you please do it rather sooner? We really need it.

Thanks in advance!

**Comment by alzheltkovskiy-hubspot** [comment]
Hello @pyromaniac. At this moment, we are working on a new SDK version where we going to add this API. We will send you our response when we release it.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @pyromaniac . Could you please check the latest [version](https://github.com/HubSpot/hubspot-api-ruby/tree/v18.0.0)?
