### ISSUE TITLE
Incorrect require order causes exception on first use

### ISSUE THREAD

**Issue by harry-m** [HubSpot/hubspot-api-ruby#26]
When I followed the installation instructions and tried to `require 'hubspot-api-client'`, the gem throws an exception:

`/Users/harry/.rvm/gems/ruby-2.6.3/gems/hubspot-api-client-2.1.0/lib/hubspot/codegen/crm/tickets/api/basic_api.rb:19:in `<class:BasicApi>': uninitialized constant Hubspot::Helpers (NameError)`

It appears that this require statement in `hubspot-api-client.rb:19` is to blame:

`Dir["#{ROOT_PATH}/hubspot/**/*.rb"].each { |f| require f }`

As it's not ordered, and so the files are not being loaded in the order assumed. Adding: 

`require_relative 'hubspot/helpers/get_all_helper.rb'`

before that statement resolves the issue, but requires editing the gem.

**Comment by uyermolkin-hubspot** [comment]
@harry-m, can you describe how did you install the gem and what exactly did you do after that? Thanks!

**Comment by harry-m** [comment]
I added it in `Gemfile`:

`gem 'hubspot-api-client', :git => 'https://github.com/HubSpot/hubspot-api-ruby.git'`

And then ran `bundle`. Before this problem I wasn't installing it from git, but I had the issue both ways.

**Comment by uyermolkin-hubspot** [comment]
@harry-m, do you run some command, e.g. `Hubspot::Crm::Tickets::BasicApi.new.create`?
Or, right when `bundle` is running, error has come?

**Comment by harry-m** [comment]
No, it doesn't get that far - it fails when the gem is required.

**Comment by yfaktor** [comment]
@harry-m could you please post screenshots of each step you are taking to install - or screen video which would be even better. Many thanks

**Comment by misterizzo** [comment]
FYI - my developer team is also encountering this same issue.

**Comment by uyermolkin-hubspot** [comment]
Gem is updated. The reason of problem was in difference of environment variables on mac and linux.
https://github.com/HubSpot/hubspot-api-ruby/commit/25d59ea58459dd24e359e9043dc7dad4019e095b

**Comment by yfaktor** [comment]
closing, please reopen if it still exists
