### ISSUE TITLE
Client triggers Secondly API rate limits

### ISSUE THREAD

**Issue by harry-m** [HubSpot/hubspot-api-ruby#27]
I'm currently using the deals search API, but it's causing the API rate limit to trigger.

```
   dealsearch = Hubspot::Crm::Deals::SearchApi.new
    after = 0
    deals = []

    loop do
      deals_page = dealsearch.do_search(
        body: {
          filterGroups: [
            {
              filters: [
                { propertyName: 'pipeline', operator: 'EQ', value: Settings['hubspot']['pipeline'] }
              ]
            }
          ],
          limit: 100,
          after: after
        }
      )

      deals.concat(deals_page.results)

      break if deals_page.paging.nil?

      after = deals_page.paging._next.after
    end
```

This triggers the rate limit on the second call to `do_search` -- but I think I am correctly re-calling the API with the `after` parameter in order to get my full list of results.

Since these rate limits are quite aggressive, it would be nice if the API client recognised and dealt with them - perhaps by blocking and waiting a while before subsequent requests are made. I had a look but couldn't see a way to do this.

I've resolved the issue now by adding `sleep(1)` after the `break`.

**Comment by uyermolkin-hubspot** [comment]
There are two ways, described in sample apps, how to avoid rate limits.
https://github.com/HubSpot/hubspot-api-ruby/tree/master/sample-apps/leaky-bucket-app
https://github.com/HubSpot/hubspot-api-ruby/tree/master/sample-apps/rate-limits-redis-sample-app

**Comment by yfaktor** [comment]
closing it as it was answered - please reopen if there are more questions, thanks!
