### ISSUE TITLE
Calling the get all for companies fail

### ISSUE THREAD

**Issue by wft-dev** [HubSpot/hubspot-api-ruby#28]
So, while using this gem, I have used this script 
```
basic_api = Hubspot::Crm::Companies::BasicApi.new
answer = basic_api.get_all
puts answer 
```

which returns the error 
```
.rvm/gems/ruby-2.6.3/gems/hubspot-api-client-2.2.0/lib/hubspot/codegen/crm/companies/models/collection_response_simple_public_object.rb:174:in `const_get': uninitialized constant Hubspot::Crm::Companies::SimplePublicObject (NameError)
Did you mean?  Hubspot::Crm::Companies::SimplePublicObjectId
               Hubspot::Crm::Companies::SimplePublicObjectInput
```

**Comment by ErmolkinVlad** [comment]
Fixed!
Two models of companies client were missed.
https://github.com/HubSpot/hubspot-api-ruby/commit/2fa22daa5b17e8eeec2fb5a249bfcd495da91654

**Comment by wft-dev** [comment]
> Fixed!
> Two models of companies client were missed.
> [2fa22da](https://github.com/HubSpot/hubspot-api-ruby/commit/2fa22daa5b17e8eeec2fb5a249bfcd495da91654)

There's still an error
```
.rvm/gems/ruby-2.6.3/gems/hubspot-api-client-2.3.1/lib/hubspot/helpers/get_all_helper.rb:19:in `block in get_all': undefined method `present?' for nil:NilClass (NoMethodError)
```

**Comment by ErmolkinVlad** [comment]
https://github.com/HubSpot/hubspot-api-ruby/commit/b9112adaa69cb8a6ed194b63bbecd48da1399fb0
It's fixed.
Can you tell which environment do you use in development: Rails, Sinatra of pure Ruby? Maybe something else?

**Comment by wft-dev** [comment]
Rails Environment.
