### ISSUE TITLE
Fix example for BatchAPI

### ISSUE THREAD

**Issue by woidda** [HubSpot/hubspot-api-ruby#51]
The exmple in [create.rb](https://github.com/HubSpot/hubspot-api-ruby/blob/3b01420a4810e7c57fa15d8234c1eb0d1c5a56bd/sample-apps/companies-app/app/lib/services/hubspot/associations/create.rb#L11
) is outdated. See [batch_api](https://github.com/HubSpot/hubspot-api-ruby/blob/4ee02321d58130e769b5d4e94de1f21d68f13853/lib/hubspot/codegen/crm/associations/api/batch_api.rb#L103)

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @woidda 
Here is workable example:
```ruby
require 'hubspot-api-client'

api_client = Hubspot::Client.new(access_token: 'YOUR_ACCESS_TOKEN')

body = {
  inputs: 
    [
      {
        "from": { "id": "1" },
        "to": { "id": "12458478151" },
        "type": "contact_to_company"
      }
    ] 
}
api_response = api_client.crm.associations.batch_api.create(
  from_object_type: "contacts",
  to_object_type: "companies",
  body: body
)
puts api_response
```
More examples you can find [here](https://developers.hubspot.com/docs/api/crm/associations).

**Comment by woidda** [comment]
Thanks for your reply. Well, this was 3 years ago. I actually had figured it out how to use the API back then. This issue was more like a reminder for you folks to update the Readme as some people might struggle with the usage.

**Comment by alzheltkovskiy-hubspot** [comment]
@woidda 
Can i close this issue?

**Comment by woidda** [comment]
> @woidda 
> Can i close this issue?

If the Readme is updated, yes ;-)

**Comment by alzheltkovskiy-hubspot** [comment]
@woidda 
`README` has link to documentation which collect workable examples.
