### ISSUE TITLE
Fix contacts search example

### ISSUE THREAD

**Issue by majksner** [HubSpot/hubspot-api-ruby#56]
Contacts search example is not working, it returns wrong contacts when searching by email.

**Comment by uyermolkin-hubspot** [comment]
@majksner can you give more information about how to reproduce this bug? Because it works for me.

**Comment by majksner** [comment]
It works with updated version of the gem, some of previous versions didn't work

**Comment by seeReadCode** [comment]
@uyermolkin-hubspot is there an example anywhere of how to search via email or any other property?
