### ISSUE TITLE
Ruby 1.9 support

### ISSUE THREAD

**Issue by jschroed91** [HubSpot/hubspot-api-ruby#59]
Hi there!

The gemspec specifies that ruby version `>= 1.9` is supported, however there are language features used in the library that require ruby `>= 2.0`. The one that I know of specifically is the use of **Keyword Arguments** which were introduced in 2.0. It looks like there are also usages of `%i` or similar syntax.

It'd be great if those could be refactored to provide support for 1.9 still, however if that's not in the cards then I'd recommend updating the gemspec to >= 2.0 at least. It doesn't seem like it'd be too much effort to fix these so that they support 1.9

## Details
Details on compatibility issues with 1.9 that I came across:

There are **27 issues** total in the lib directory. 

**24 instances of `%i` usage** which are in the `api_client.rb` files for the methods attribute. 

> Just pulled out two examples but it's in all of the api_client files:
> https://github.com/HubSpot/hubspot-api-ruby/blob/e0535ba27fad260c2ee13801d6e863098ecf8e44/lib/hubspot/codegen/crm/contacts/api_client.rb#L76
> https://github.com/HubSpot/hubspot-api-ruby/blob/e0535ba27fad260c2ee13801d6e863098ecf8e44/lib/hubspot/codegen/crm/companies/api_client.rb#L76

**3 methods using Keyword Arguments**

https://github.com/HubSpot/hubspot-api-ruby/blob/e0535ba27fad260c2ee13801d6e863098ecf8e44/lib/hubspot/exceptions.rb#L5

https://github.com/HubSpot/hubspot-api-ruby/blob/e0535ba27fad260c2ee13801d6e863098ecf8e44/lib/hubspot/oauth_helper.rb#L5

https://github.com/HubSpot/hubspot-api-ruby/blob/e0535ba27fad260c2ee13801d6e863098ecf8e44/lib/hubspot/helpers/webhooks_helper.rb#L4-L11

**Comment by jschroed91** [comment]
Actually - after looking into this further, I believe there are more issues with 1.9 support beyond what I detailed above.

Some of the dependency version constraints result in dependencies that don't support 1.9, and there are also other compatibility issues within the lib code itself that would need to be addressed. So it may not be worthwhile for you all to support

**Comment by jschroed91** [comment]
Opened a pull request from a branch I have in my fork that supports ruby 1.9. I don't think this should be merged into master branch but maybe it's worth having a separate branch for 1.9 support? If not, that's fine too, figured I'd open it in case it's helpful to someone else #60

**Comment by plaurynovich-hubspot** [comment]
Hi, @jschroed91. Required ruby version has been updated to 2.7 since v14.0.0. Thank you.
