### ISSUE TITLE
config.error_handler

### ISSUE THREAD

**Issue by jacobjlevine** [HubSpot/hubspot-api-ruby#84]
Hi folks, I've recently run into a situation where I'm experiencing throttling issues with HubSpot's API. The weird thing is that I set config.error_handler with values for responding to 429 errors such that this should never happen. To better understand what was going on, I tried looking through the gem files to see if I could understand what I was doing wrong. Except, when I just went looking, I actually didn't see any reference to to the error_handler configuration or its related attributes except in comments and README files. Am I missing something? Or was that functionality for that configuration setting never actually developed for this gem?

**Comment by jacobjlevine** [comment]
In case anyone else is struggling with this, here's an ugly workaround.

```
module Hubspot
  module Crm
    module Contacts
      module ApiClientWrapper
        # This is an ugly hack because HubSpot doesn't appear to have actually implemented this functionality in their gem.
        def call_api(*args)
          retry_number = max_retries = seconds_delay = 0
          last_error = nil

          while retry_number <= max_retries
            sleep seconds_delay

            begin
              return super(*args)
            rescue ApiError => e
              last_error = e
              error_config = get_error_config(e.code,config.error_handler)

              if error_config
                max_retries = error_config[:max_retries]
                seconds_delay = error_config[:seconds_delay]
              else
                max_retries = 0
              end

              retry_number += 1
            end
          end

          raise last_error if last_error
        end

        def get_error_config(code, error_handler)
          error_handler.each do |k,v|
            if (k.is_a?(Array) && k.include?(code)) || code == k
              return v
            end
          end

          return
        end
      end

      class ApiClient
        prepend ApiClientWrapper
      end
    end
  end
end
```

In case it helps, I have an app/overrides directory where I put code like this. I've also included the below code in my config/application.rb file.

```
# This pattern allows for re-opening gem modules and classes without violating Zeitwerk's autoloading rules.
overrides = "#{Rails.root}/app/overrides"
Rails.autoloaders.main.ignore(overrides)

config.to_prepare do
  Dir.glob("#{overrides}/**/*.rb").each do |override|
    load override
  end
end
```

**Comment by ketiko** [comment]
I was also looking through this and never found `error_handler` being used for anything.

**Comment by MH4GF** [comment]
Hi, maybe the error handling code was erased in this commit?
https://github.com/HubSpot/hubspot-api-ruby/commit/95dc2e4dfb87e97ba3f72a1f4c7755413ea5a790

It used to use the error_handler block.
https://github.com/HubSpot/hubspot-api-ruby/blob/52708690cd0c2a6db76fa770744cf89032c7118a/lib/hubspot/codegen/crm/companies/api_client.rb#L69-L81
