### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by EtienneDepaulis** [HubSpot/hubspot-api-ruby#90]
Hello,

the usage of this gem prompt some warnings when you are using tools like diffend.io as this gem has no license.
Can you decide on a license and configure it in your gemspec ?

Best regards

**Comment by plaurynovich-hubspot** [comment]
Hello,

the license was added in 9.6.0.

Thank you

**Comment by EtienneDepaulis** [comment]
Awesome thx :)
